import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    // Nav
    dashboard: 'Dashboard',
    trends: 'Trends',
    bioAge: 'Bio Age',
    logEntry: 'Log Entry',
    journal: 'Daily Journal',
    connectDevices: 'Connect Devices',
    labResults: 'Lab Results',
    biologicalAge: 'Biological Age',
    healthCoach: 'Health Coach',
    more: 'More',
    coach: 'Coach',
    signOut: 'Sign Out',

    // Dashboard
    todaysVitals: "Today's Vitals",
    noDataLogged: 'No data logged today',
    noDataDesc: 'Log your health metrics to see your recovery score, energy level, and sleep summary.',
    logHealthMetrics: 'Log Health Metrics',
    logToday: 'Log Today',
    restingHR: 'Resting HR',
    averageResting: 'Average resting',
    heartRateVariability: 'Heart rate variability',
    workoutIntensity: 'Workout intensity',
    goalReached: 'Goal reached!',
    toGoal: 'to goal',
    notes: 'Notes',
    strain: 'Strain',
    steps: 'Steps',

    // Recovery gauge / energy bar / sleep summary
    recoveryScore: 'Recovery Score',
    energyLevel: 'Energy Level',
    sleepSummary: 'Sleep Summary',
    noSleepData: 'No sleep data for today',
    duration: 'Duration',
    quality: 'Quality',
    targetSleep: 'Target: 7-9 hrs',
    recoveryExcellent: 'Excellent',
    recoveryGood: 'Good',
    recoveryModerate: 'Moderate',
    recoveryLow: 'Low',
    recoveryPoor: 'Poor',
    energyHigh: 'High Energy',
    energyMed: 'Moderate',
    energyLow: 'Low Energy',
    energyRest: 'Rest Day',
    energyNoData: 'No Data',

    // Log Entry
    logEntryTitle: 'Log Health Data',
    logEntryDesc: 'Track your daily health metrics',
    logMetrics: 'Log Metrics',
    updateEntryDesc: 'Update your entry for this date',
    recordDailyVitals: 'Record your daily vitals',
    save: 'Save',
    saving: 'Saving…',
    savedSuccess: 'Saved successfully!',
    date: 'Date',
    heartRate: 'Heart Rate',
    restingHeartRate: 'Resting Heart Rate',
    hrv: 'HRV',
    heartRateVariabilityFull: 'Heart Rate Variability',
    sleepDuration: 'Sleep Duration',
    sleepQuality: 'Sleep Quality',
    workoutStrain: 'Workout Strain',
    stepsLabel: 'Steps',
    notesLabel: 'Notes',
    howAreYouFeeling: 'How are you feeling today?',
    saveEntry: 'Save Entry',
    updateEntry: 'Update Entry',
    savingDots: 'Saving...',
    savedExcl: 'Saved!',
    hours: 'hours',

    // Trends
    trendsTitle: 'Trends',
    trendsDesc: 'Your health data over time',
    trackOverTime: 'Track your health metrics over time',
    noDataPeriod: 'No data available for the selected period',
    startLogging: 'Start logging your health metrics to see trends',
    days7: '7 Days',
    days30: '30 Days',
    avg: 'Avg',

    // Trend chart names
    trendRecovery: 'Recovery Score',
    trendHrv: 'HRV',
    trendHeartRate: 'Resting Heart Rate',
    trendSleepDuration: 'Sleep Duration',
    trendSleepQuality: 'Sleep Quality',
    trendSteps: 'Steps',
    trendStrain: 'Workout Strain',

    // Bio Age
    biologicalAgeTitle: 'Biological Age',
    biologicalAgeDesc: "Your body's true age based on health biomarkers",
    notEnoughData: 'Not enough data yet',
    notEnoughDataDesc: 'Log at least 5 days of health data to calculate your biological age. The more data, the more accurate the estimate.',
    estimatesOnly: 'Estimates only · not medical advice',
    bioAgeLabel: 'Biological Age',
    chronologicalAge: 'Chronological age',
    yrs: 'yrs',
    atChronoAge: 'At your chronological age',
    yngrThanReal: 'younger than real age',
    oldrThanReal: 'older than real age',
    yr: 'yr',
    basedOnDays: 'Based on',
    daysLogged: 'days of logged health data · estimates improve with more data',
    bioAgeDisclaimer: 'Biological age estimates are based on your logged health metrics (HRV, sleep, activity, recovery). These are statistical approximations and are',
    notMedDiagnosis: 'not a medical diagnosis',
    bioAgeDisclaimerEnd: '. Consult a healthcare professional for clinical assessment. Chronological age is set to',
    updateInProfile: '— update in your profile for personalized results.',
    systemOverview: 'System Overview',
    bioSystemsRadar: 'Biological systems radar',
    yourSystems: 'Your systems',
    higherYounger: 'Higher = younger',
    bioAgeTrend: '6-Month Trend',
    bioAgeOverTime: 'Biological age over time',
    needMoreTrendData: 'Need at least 3 days of data per month to plot trend',
    realAge: 'Real age',
    bioAgeTooltipAge: 'Age',
    optimal: 'Optimal',
    needsAttention: 'Needs attention',

    // Journal
    journalTitle: 'My Experiments',
    journalSubtitle: 'Daily habits · Lifestyle correlations',
    journalDesc: 'Track daily habits and lifestyle factors',
    morningCheckin: 'Morning check-in available',
    morningCheckinDesc: 'Takes ~60 seconds. Track your habits to unlock insights.',
    correlations: 'Correlations',
    journalLog: 'Journal Log',
    notEnoughDataJournal: 'Not enough data yet',
    notEnoughDataJournalDesc: 'Complete at least',
    dailyCheckins: 'daily check-ins',
    toUnlock: 'to unlock lifestyle correlations. You have',
    soFar: 'so far.',
    checkinsComplete: 'check-ins complete',
    startCheckin: "Start Today's Check-in",
    noCorrelations: 'No significant correlations found',
    noCorrelationsDesc: 'Try a different filter, or keep logging to find patterns.',
    rankedBy: 'Ranked by correlation strength. Based on',
    daysCheckins: 'days of check-ins.',
    noEntriesYet: 'No entries yet',
    noEntriesDesc: 'Start your first daily check-in to see it here.',
    today: '📅 Today',
    yesterday: 'Yesterday',
    questionsAnswered: 'questions answered',
    edit: 'Edit',
    checkIn: 'Check In',
    todayDone: 'Today ✓',

    // Journal questions
    jqSunlight: 'Sunlight Exposure',
    jqSunlightDesc: 'Minutes outside in natural light',
    jqWater: 'Water Intake',
    jqWaterDesc: 'Total water consumed (ml)',
    jqAlcohol: 'Alcohol',
    jqAlcoholDesc: 'Standard drinks consumed',
    jqStress: 'Stress Level',
    jqStressDesc: 'Overall stress today',
    jqExercise: 'Exercise',
    jqExerciseDesc: 'Intentional exercise minutes',
    jqScreen: 'Screen Before Bed',
    jqScreenDesc: 'Screen time in the hour before sleep',
    jqCaffeine: 'Caffeine',
    jqCaffeineDesc: 'Total caffeine intake (mg)',
    jqLastCaffeine: 'Last Caffeine Time',
    jqLastCaffeineDesc: 'Hour of last caffeine (0–23)',
    jqMeditation: 'Meditation',
    jqMeditationDesc: 'Meditation or breathing time',
    jqCold: 'Cold Exposure',
    jqColdDesc: 'Cold shower or ice bath',
    jqMood: 'Mood',
    jqMoodDesc: 'Overall mood today',
    relaxed: 'Relaxed',
    overwhelmed: 'Overwhelmed',
    low: 'Low',
    high: 'High',
    yes: 'Yes',
    no: 'No',

    // Daily checkin
    dailyCheckinTitle: 'Daily Check-in',
    of: 'of',
    customiseQuestions: 'Customise Questions',
    chooseHabits: 'Choose which habits you want to track daily.',
    savePreferences: 'Save Preferences',
    back: 'Back',
    skip: 'Skip',
    next: 'Next',
    saveCheckin: 'Save Check-in',

    // Health metrics (correlation filter)
    hmSleepScore: 'Sleep Score',
    hmHrv: 'HRV',
    hmRecovery: 'Recovery Score',
    hmSleepDuration: 'Sleep Duration',
    hmRestingHR: 'Resting Heart Rate',

    // Correlation card
    strongCorrelation: 'Strong',
    moderateCorrelation: 'Moderate',
    weakCorrelation: 'Weak',
    positiveCorrelation: 'Positive',
    negativeCorrelation: 'Negative',
    basedOn: 'Based on',
    days: 'days',

    // Lab Results
    labResultsTitle: 'Lab Results',
    labResultsDesc: 'Your medical records, documents, and test results',
    addRecord: 'Add Record',
    searchRecords: 'Search records, notes, categories…',
    noRecordsYet: 'No records yet',
    noMatchesFound: 'No matches found',
    uploadFirstLab: 'Upload your first lab result, scan, or medical document to get started.',
    tryAdjusting: 'Try adjusting your search or filter.',
    addFirstRecord: 'Add First Record',
    record: 'record',
    records: 'records',
    catAll: 'All',
    catBloodWork: 'Blood Work',
    catImaging: 'Imaging',
    catUrine: 'Urine',
    catHormone: 'Hormone Panel',
    catOther: 'Other',
    // Lab upload form
    editRecord: 'Edit Record',
    addLabResult: 'Add Lab Result',
    title: 'Title',
    category: 'Category',
    selectCategory: 'Select…',
    document: 'Document',
    pdfOrImage: '(PDF or image)',
    dropFileHere: 'Drop file here or',
    browse: 'browse',
    pdfSizeLimit: 'PDF, JPG, PNG up to 25MB',
    existingFile: 'Existing file',
    uploadNewToReplace: '(upload new to replace)',
    cancel: 'Cancel',
    uploading: 'Uploading…',
    update: 'Update',
    saveRecord: 'Save Record',
    selectCategorySheet: 'Select Category',
    invalidFileType: 'Please upload a PDF or image file',
    recordUpdated: 'Record updated',
    labResultSaved: 'Lab result saved',
    // Lab detail modal
    noDocAttached: 'No document attached',
    notesLabel: 'Notes',
    download: 'Download',
    delete: 'Delete',
    deleteFailMsg: 'Failed to delete record',
    deleteSuccessMsg: 'Record deleted',

    // Connect Devices
    connectDevicesTitle: 'Connect Devices',
    connectDevicesDesc: 'Sync your wearables and health apps',
    linkWearables: 'Link your wearables and health platforms to sync data automatically',
    syncAll: 'Sync All',
    syncing: 'Syncing…',
    synced: 'Synced!',
    connected: 'Connected',
    available: 'Available',
    linked: 'linked',
    oauthComing: 'OAuth integration coming soon.',
    oauthDesc: 'Connection status is saved to your account. Full real-time sync will be available when platform integrations launch.',
    notConnected: 'Not Connected',
    lastSynced: 'Last synced',
    neverSynced: 'Never synced',
    connectToSync: 'Connect to start syncing',
    connect: 'Connect',
    disconnect: 'Disconnect',
    deviceConnected: 'connected',
    deviceDisconnected: 'disconnected',
    syncedDevices: 'Synced',
    deviceSport: 'Sports Watch',
    deviceFitness: 'Fitness Tracker',
    deviceRecovery: 'Recovery Tracker',
    deviceRing: 'Smart Ring',
    deviceSmartphone: 'Smartphone Platform',

    // Account / Settings
    settings: 'Settings',
    currentPlan: 'Current Plan',
    upgrade: 'Upgrade',
    notifications: 'Notifications',
    units: 'Units',
    connectedDevices: 'Connected Devices',
    privacySettings: 'Privacy Settings',
    helpSupport: 'Help & Support',
    language: 'Language',
    deleteAccount: 'Delete Account',
    deleteAccountTitle: 'Delete Account?',
    deleteAccountDesc: 'This will permanently delete your account and all associated data — including health logs, lab results, journal entries, and device connections. This action cannot be undone.',
    deleteMyAccount: 'Delete My Account',
    deleting: 'Deleting…',
    achievements: 'Achievements',
    earned: 'Earned',
    friends: 'Friends',
    addFriend: 'Add Friend',
    invite: 'Invite',
    orShareLink: 'Or share your invite link',
    enterUsernameEmail: 'Enter username or email…',
    noFriendsYet: 'No friends yet',
    noFriendsDesc: 'Invite friends to compare streaks and recovery scores',
    member: 'Member',
    memberSince: 'Member since',
    dayStreak: 'Day Streak',
    keepItUp: 'Keep it up!',
    noActiveStreak: 'No active streak',
    restartStreak: 'Restart your streak! 💡',
    couldntLoadProfile: "Couldn't load profile",
    checkConnection: 'Please check your connection and try again.',

    // Health Coach
    healthCoachTitle: 'Health Coach',
  },
  zh: {
    // Nav
    dashboard: '仪表盘',
    trends: '趋势',
    bioAge: '生物年龄',
    logEntry: '记录数据',
    journal: '每日日记',
    connectDevices: '连接设备',
    labResults: '检验报告',
    biologicalAge: '生物年龄',
    healthCoach: '健康教练',
    more: '更多',
    coach: '教练',
    signOut: '退出登录',

    // Dashboard
    todaysVitals: '今日健康数据',
    noDataLogged: '今日暂无数据',
    noDataDesc: '记录您的健康指标，查看恢复评分、能量水平和睡眠摘要。',
    logHealthMetrics: '记录健康指标',
    logToday: '立即记录',
    restingHR: '静息心率',
    averageResting: '平均静息',
    heartRateVariability: '心率变异性',
    workoutIntensity: '运动强度',
    goalReached: '已达目标！',
    toGoal: '距目标',
    notes: '备注',
    strain: '运动负荷',
    steps: '步数',

    // Recovery gauge / energy bar / sleep summary
    recoveryScore: '恢复评分',
    energyLevel: '能量水平',
    sleepSummary: '睡眠摘要',
    noSleepData: '今日暂无睡眠数据',
    duration: '时长',
    quality: '质量',
    targetSleep: '目标：7-9 小时',
    recoveryExcellent: '极佳',
    recoveryGood: '良好',
    recoveryModerate: '一般',
    recoveryLow: '偏低',
    recoveryPoor: '较差',
    energyHigh: '高能量',
    energyMed: '中等',
    energyLow: '低能量',
    energyRest: '休息日',
    energyNoData: '暂无数据',

    // Log Entry
    logEntryTitle: '记录健康数据',
    logEntryDesc: '追踪您的每日健康指标',
    logMetrics: '记录指标',
    updateEntryDesc: '更新该日期的记录',
    recordDailyVitals: '记录每日健康数据',
    save: '保存',
    saving: '保存中…',
    savedSuccess: '保存成功！',
    date: '日期',
    heartRate: '心率',
    restingHeartRate: '静息心率',
    hrv: '心率变异性',
    heartRateVariabilityFull: '心率变异性',
    sleepDuration: '睡眠时长',
    sleepQuality: '睡眠质量',
    workoutStrain: '运动负荷',
    stepsLabel: '步数',
    notesLabel: '备注',
    howAreYouFeeling: '今天感觉怎么样？',
    saveEntry: '保存记录',
    updateEntry: '更新记录',
    savingDots: '保存中...',
    savedExcl: '已保存！',
    hours: '小时',

    // Trends
    trendsTitle: '健康趋势',
    trendsDesc: '您的健康数据变化',
    trackOverTime: '追踪您的健康指标变化',
    noDataPeriod: '所选时间段暂无数据',
    startLogging: '开始记录健康数据以查看趋势',
    days7: '7天',
    days30: '30天',
    avg: '均值',

    // Trend chart names
    trendRecovery: '恢复评分',
    trendHrv: '心率变异性',
    trendHeartRate: '静息心率',
    trendSleepDuration: '睡眠时长',
    trendSleepQuality: '睡眠质量',
    trendSteps: '步数',
    trendStrain: '运动负荷',

    // Bio Age
    biologicalAgeTitle: '生物年龄',
    biologicalAgeDesc: '基于健康生物标志物的身体真实年龄',
    notEnoughData: '数据不足',
    notEnoughDataDesc: '请至少记录5天的健康数据以计算您的生物年龄。数据越多，估算越准确。',
    estimatesOnly: '仅供参考 · 非医疗建议',
    bioAgeLabel: '生物年龄',
    chronologicalAge: '实际年龄',
    yrs: '岁',
    atChronoAge: '与实际年龄相同',
    yngrThanReal: '比实际年龄年轻',
    oldrThanReal: '比实际年龄偏老',
    yr: '岁',
    basedOnDays: '基于',
    daysLogged: '天的健康数据 · 数据越多估算越准确',
    bioAgeDisclaimer: '生物年龄估算基于您记录的健康指标（心率变异性、睡眠、活动量、恢复情况），属于统计近似值，',
    notMedDiagnosis: '非医疗诊断',
    bioAgeDisclaimerEnd: '。请咨询医疗专业人员进行临床评估。实际年龄已设置为',
    updateInProfile: '——请在个人资料中更新以获得个性化结果。',
    systemOverview: '系统概览',
    bioSystemsRadar: '生理系统雷达图',
    yourSystems: '您的系统',
    higherYounger: '越高 = 越年轻',
    bioAgeTrend: '6个月趋势',
    bioAgeOverTime: '生物年龄变化',
    needMoreTrendData: '每月至少需要3天数据才能绘制趋势',
    realAge: '实际年龄',
    bioAgeTooltipAge: '年龄',
    optimal: '最优',
    needsAttention: '需关注',

    // Journal
    journalTitle: '我的实验',
    journalSubtitle: '每日习惯 · 生活方式相关性',
    journalDesc: '追踪每日习惯和生活方式',
    morningCheckin: '晨间打卡',
    morningCheckinDesc: '约60秒完成。追踪习惯，解锁健康洞察。',
    correlations: '相关性分析',
    journalLog: '日记记录',
    notEnoughDataJournal: '数据不足',
    notEnoughDataJournalDesc: '至少完成',
    dailyCheckins: '次每日打卡',
    toUnlock: '以解锁生活方式相关性。目前已有',
    soFar: '条记录。',
    checkinsComplete: '次打卡已完成',
    startCheckin: '开始今日打卡',
    noCorrelations: '未发现显著相关性',
    noCorrelationsDesc: '请尝试不同的筛选条件，或继续记录以发现规律。',
    rankedBy: '按相关强度排序。基于',
    daysCheckins: '天的打卡数据。',
    noEntriesYet: '暂无记录',
    noEntriesDesc: '完成第一次每日打卡，即可在此查看。',
    today: '📅 今天',
    yesterday: '昨天',
    questionsAnswered: '题已回答',
    edit: '编辑',
    checkIn: '打卡',
    todayDone: '今日 ✓',

    // Journal questions
    jqSunlight: '阳光暴露',
    jqSunlightDesc: '户外自然光照时间（分钟）',
    jqWater: '饮水量',
    jqWaterDesc: '总饮水量（ml）',
    jqAlcohol: '饮酒',
    jqAlcoholDesc: '标准饮酒单位',
    jqStress: '压力水平',
    jqStressDesc: '今日整体压力',
    jqExercise: '运动',
    jqExerciseDesc: '主动运动时间（分钟）',
    jqScreen: '睡前屏幕时间',
    jqScreenDesc: '睡前一小时内的屏幕使用时间',
    jqCaffeine: '咖啡因',
    jqCaffeineDesc: '总咖啡因摄入量（mg）',
    jqLastCaffeine: '最后一次咖啡因时间',
    jqLastCaffeineDesc: '最后一次摄入咖啡因的小时（0–23）',
    jqMeditation: '冥想',
    jqMeditationDesc: '冥想或呼吸练习时间',
    jqCold: '冷水浴',
    jqColdDesc: '冷水淋浴或冰浴',
    jqMood: '心情',
    jqMoodDesc: '今日整体心情',
    relaxed: '放松',
    overwhelmed: '崩溃',
    low: '低',
    high: '高',
    yes: '是',
    no: '否',

    // Daily checkin
    dailyCheckinTitle: '每日打卡',
    of: '/',
    customiseQuestions: '自定义问题',
    chooseHabits: '选择您每天想要追踪的习惯。',
    savePreferences: '保存偏好',
    back: '返回',
    skip: '跳过',
    next: '下一步',
    saveCheckin: '保存打卡',

    // Health metrics (correlation filter)
    hmSleepScore: '睡眠评分',
    hmHrv: '心率变异性',
    hmRecovery: '恢复评分',
    hmSleepDuration: '睡眠时长',
    hmRestingHR: '静息心率',

    // Correlation card
    strongCorrelation: '强',
    moderateCorrelation: '中',
    weakCorrelation: '弱',
    positiveCorrelation: '正相关',
    negativeCorrelation: '负相关',
    basedOn: '基于',
    days: '天',

    // Lab Results
    labResultsTitle: '检验报告',
    labResultsDesc: '您的医疗记录、文件和检测结果',
    addRecord: '添加记录',
    searchRecords: '搜索记录、备注、类别…',
    noRecordsYet: '暂无记录',
    noMatchesFound: '未找到匹配项',
    uploadFirstLab: '上传您的第一份检验报告、扫描件或医疗文件以开始。',
    tryAdjusting: '请调整搜索条件或筛选项。',
    addFirstRecord: '添加首条记录',
    record: '条记录',
    records: '条记录',
    catAll: '全部',
    catBloodWork: '血液检查',
    catImaging: '影像检查',
    catUrine: '尿液检查',
    catHormone: '激素检测',
    catOther: '其他',
    // Lab upload form
    editRecord: '编辑记录',
    addLabResult: '添加检验报告',
    title: '标题',
    category: '类别',
    selectCategory: '请选择…',
    document: '文件',
    pdfOrImage: '（PDF或图片）',
    dropFileHere: '将文件拖拽至此或',
    browse: '浏览',
    pdfSizeLimit: 'PDF、JPG、PNG，最大25MB',
    existingFile: '已有文件',
    uploadNewToReplace: '（上传新文件以替换）',
    cancel: '取消',
    uploading: '上传中…',
    update: '更新',
    saveRecord: '保存记录',
    selectCategorySheet: '选择类别',
    invalidFileType: '请上传PDF或图片文件',
    recordUpdated: '记录已更新',
    labResultSaved: '检验报告已保存',
    // Lab detail modal
    noDocAttached: '未附加文件',
    notesLabel: '备注',
    download: '下载',
    delete: '删除',
    deleteFailMsg: '删除记录失败',
    deleteSuccessMsg: '记录已删除',

    // Connect Devices
    connectDevicesTitle: '连接设备',
    connectDevicesDesc: '同步您的可穿戴设备和健康应用',
    linkWearables: '连接您的可穿戴设备和健康平台，自动同步数据',
    syncAll: '全部同步',
    syncing: '同步中…',
    synced: '已同步！',
    connected: '已连接',
    available: '可用',
    linked: '已连接',
    oauthComing: 'OAuth 集成即将推出。',
    oauthDesc: '连接状态已保存至您的账户。平台集成上线后将支持实时同步。',
    notConnected: '未连接',
    lastSynced: '上次同步',
    neverSynced: '从未同步',
    connectToSync: '连接以开始同步',
    connect: '连接',
    disconnect: '断开连接',
    deviceConnected: '已连接',
    deviceDisconnected: '已断开',
    syncedDevices: '已同步',
    deviceSport: '运动手表',
    deviceFitness: '健身追踪器',
    deviceRecovery: '恢复追踪器',
    deviceRing: '智能戒指',
    deviceSmartphone: '智能手机平台',

    // Account / Settings
    settings: '设置',
    currentPlan: '当前套餐',
    upgrade: '升级',
    notifications: '通知',
    units: '单位',
    connectedDevices: '已连接设备',
    privacySettings: '隐私设置',
    helpSupport: '帮助与支持',
    language: '语言',
    deleteAccount: '删除账户',
    deleteAccountTitle: '删除账户？',
    deleteAccountDesc: '这将永久删除您的账户及所有相关数据，包括健康日志、检验报告、日记和设备连接。此操作无法撤销。',
    deleteMyAccount: '删除我的账户',
    deleting: '删除中…',
    achievements: '成就',
    earned: '已获得',
    friends: '好友',
    addFriend: '添加好友',
    invite: '邀请',
    orShareLink: '或分享您的邀请链接',
    enterUsernameEmail: '输入用户名或邮箱…',
    noFriendsYet: '暂无好友',
    noFriendsDesc: '邀请好友比较连续记录天数和恢复评分',
    member: '会员',
    memberSince: '加入时间',
    dayStreak: '天连续记录',
    keepItUp: '继续保持！',
    noActiveStreak: '暂无连续记录',
    restartStreak: '重新开始吧！💡',
    couldntLoadProfile: '无法加载个人资料',
    checkConnection: '请检查网络连接后重试。',

    // Health Coach
    healthCoachTitle: '健康教练',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('app_lang') || 'en');

  const switchLanguage = (newLang) => {
    setLang(newLang);
    localStorage.setItem('app_lang', newLang);
  };

  const t = (key) => translations[lang]?.[key] ?? translations['en'][key] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, switchLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}